version: '3.7'
services:
  # PHP Service
  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    ports:
      - '9001:9000'
    volumes:
      - ./sys_app:/var/www/html
      - ./scripts:/var/www/html/scripts
    networks:
      - app-network
  
  # Webserver Service
  server:
    image: nginx:alpine
    container_name: server
    restart: unless-stopped
    tty: true
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - ./sys_app:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  # Node Service - Vite
  npm:
    image: node:18-alpine
    container_name: npm
    volumes:
      - ./sys_app:/var/www/html
      - ./scripts:/var/www/html/scripts
    command: >
      sh -c "npm install && npm run dev"
    ports:
      - '5174:5174'
      - '5173:5173'
    working_dir: /var/www/html
    networks:
      - app-network

  # SQL Service
  database:
    image: mysql:8.0.33
    container_name: database
    tty: true
    restart: unless-stopped
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: mhm
        MYSQL_USER: mhm
        MYSQL_PASSWORD: Password123
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
        - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
